### ISSUE TITLE
[Simulations] Lab 13 Comments

### ISSUE THREAD

**Issue by lmock** [cs10/bjc-r#107]
If there is anything that you see that need fixing for Lab 13, please leave a comment below! Thanks!

**Comment by jassicacanidy** [comment]
In simulation-bioinformatics.topic&step=1, 2nd para:
Reads "We computer all the pairwise..." i/o "We compute all the pairwise..."

**Comment by jassicacanidy** [comment]
simulation-bioinformatics.topic&step=5

Reads "1. First, your block will search through the list to identify should find the two strings with the most overlap."
i/o "1. First, combine strings will search through the list of original strings to identify the two strings with the most overlap."

**Comment by aaaschmitt** [comment]
In the bioinformatics lab (14?) on the last page titled "Discuss this model" line reads:

"Also, think about the pros and cons of the algorithm to solve the shortest superstring problem?"

I don't think it should end in a question mark, just a period.  Otherwise I second the problems pointed out above.

**Comment by aaaschmitt** [comment]
fixed the above in lab 14.  These comments should probably be deleted or moved to a lab 14 thread.
