### ISSUE TITLE
Recursion II Lab Review

### ISSUE THREAD

**Issue by lmock** [cs10/bjc-r#122]
If there is anything that you see that needs fixing for the Recursion II lab this week, please leave a comment below! Thanks!

**Comment by cycomachead** [comment]
http://inst.eecs.berkeley.edu/~cs10/labs/topic/topic.html?topic=berkeley_bjc/recur/recursive-reporters.topic&novideo=true&noreading=true&course=berkeley_bjc.html

The Recursive Reporters: box doesn't really make any sense where it is...

**Comment by cycomachead** [comment]
http://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/recursion/recursive-reporters/ice-cream-shop.html?topic=berkeley_bjc/recur/recursive-reporters.topic&step=12&novideo=true&noreading=true&course=berkeley_bjc.html

The tip needs to link to Snap reference manual since people don't know where to find it. (Access from the Snap menu in Snap). Also, Snap should be in the snap style, and the section should be in a special font or just say 6.C since roman numerals look odd..

**Comment by cycomachead** [comment]
The quiz looks funky here:
http://bjc.eecs.berkeley.edu/bjc-r/cur/programming/recursion/recursive-reporters/recursively-sorting.html?topic=berkeley_bjc/recur/recursive-reporters.topic&step=7&novideo=true&noreading=true&course=berkeley_bjc.html

And it should probably be a quiz...

**Comment by ibirnam** [comment]
http://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/recursion/recursive-reporters/binary-numbers.html?topic=berkeley_bjc/recur/recursive-reporters.topic&step=0&novideo=true&noreading=true&course=berkeley_bjc.html

piglatin solution should be the following:
![screen shot 2013-10-28 at 3 21 14 pm](https://f.cloud.github.com/assets/1196118/1424526/fd28f702-401f-11e3-809f-be220336c922.png)

**Comment by ibirnam** [comment]
This lab is way too long. This should be split up into 2 different labs.

Also, I found the menu question to be very difficult for students to grasp (it was tough for me as well). May consider simplifying it?

Also, it would be nice to have solutions for all problems of this lab, so that students can see a working example if they can't get it.
