### ISSUE TITLE
Recursion 3 Lab

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#123]
Where doe recursion 3 fit into the current BJC course? The topic files aren't referenced anywhere, and it's missing from the labs page...

**Comment by xtitter** [comment]
Brian?

Nate fat-thumb Titterton

**Comment by xtitter** [comment]
reply@reply.github.com
Subject: Re: [bjc-r] Recursion 3 Lab (#123)
References: <beautyjoy/bjc-r/issues/123@github.com> <CACEQgj=XUMzM4Zp6avWu+Ci8FYg5EYGaLa0XLsNQ2nU918C77w@mail.gmail.com>
In-Reply-To: <CACEQgj=XUMzM4Zp6avWu+Ci8FYg5EYGaLa0XLsNQ2nU918C77w@mail.gmail.com>
Content-Type: text/plain; charset=windows-1252; format=flowed
Content-Transfer-Encoding: 7bit

There isn't a Recursion 3 any more.  But maybe you'll think Recursion 2 is too 
crowded
and should be split up.  If so, don't split it in the summer teacher prep 
course -- it's because
I had to fit everything into four weeks that I overcrowded Recursion 2.
