### ISSUE TITLE
Internet Lab

### ISSUE THREAD

**Issue by lmock** [cs10/bjc-r#130]
Please leave your comments regarding the Internet Lab below. Thanks!

**Comment by cycomachead** [comment]
Here's some comments for the Internet Lab:

On the traceroute page
It should explicitly explain how to type trace route in terminal.

The command needs to be /usr/sbin/traceroute

I think it's best if the command typing is initially separated from the output, or at least explain to students what they are supposed to do.

I think all commands should be monospaced. You can use `<code>` or `<pre>` in the HTML.

**Comment by ibirnam** [comment]
the first page should show them how to open a terminal on the Mac computers, or on their laptops (Mac and PC).

Other than that, I agree with Michael's comments.

**Comment by jcawth** [comment]
Michael is definitely correct on the command being /usr/sbin/traceroute, and the same for the ping command. I agree with the above statements and have found a few grammatical errors listed below.

on the Plain Text Connections page, the second sentence after the HTML Source heading, browser should be changed to the plural browsers.

Also, on the Connection Metrics page, when explaining the replacement with 225, i believe the sentence should be "Then replace the last digits of the IP (say XXX.YYY.ZZZ.001) address with 255" rather than the current, "The replace the last digit if the IP (say XXX.YYY.ZZZ.001) address with 255"

**Comment by peterasujan** [comment]
I'm actually not able to find "ping" at all, even in /usr/sbin/.

**Comment by cycomachead** [comment]
Ping is in `/sbin/ping` on these macs.

**Comment by ibirnam** [comment]
http://inst.eecs.berkeley.edu/~cs10/labs/cur/programming/internet/speed.html?topic=berkeley_bjc/areas/internet.topic&step=3&novideo=true&noreading=true&course=berkeley_bjc.html

Needs a definition for Throughput

**Comment by empbetty** [comment]
all above issues have been fixed
