### ISSUE TITLE
HOFs I Lab

### ISSUE THREAD

**Issue by lmock** [cs10/bjc-r#140]
Please leave comments (good and bad) below for lab feedback. Thanks!

**Comment by ibirnam** [comment]
overall great lab, though very few students seemed to get past the pandigital part. The groups that did get through it though managed to breeze through the rest of the lab (not including extra for experts).

I would suggest either making that problem easier, or putting it towards the end. otherwise no complaints!

**Comment by cycomachead** [comment]
Yeah, we should also think about the HOF-y needs of it.

It needs a little more explanation.

I think we should encourage people to draw out an iterative approach and
then try to get them to naturally approach the solution using keep.

## 

Michael Ball
http://www.michaelballphoto.com
Photos & iPhone Apps!
