### ISSUE TITLE
Making Files Run In Snap

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#180]
So, we have the `class="run"` thing, but how should we reference files when things will be served from multiple URLs / servers?

I just ran into an issue because there's files not on bjc.EECS but thats where the normal URLs point. (I 'fixed' it by pointing to CS10..)

**Comment by xtitter** [comment]
Check out getSnapRunURL() inside admin/bjc-library.js.  IIRC, we special 
cased things because there was no easy answer, iirc.   You could add the 
particular domain you want handled in there, maybe?

   <-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><-><=><->
   Nathaniel Titterton, Ph.D.                    nate@berkeley.edu
   Computer Science Education         U.C. Berkeley, 329 Soda Hall
