### ISSUE TITLE
The FOR block

### ISSUE THREAD

**Issue by brianharvey** [cs10/bjc-r#189]
In the first line, "like" should be "as."  Also, that paragraph needs to make clear (even though it should be familiar) that the "1" and "10" are changeable, e.g., "1 in this example."

In the second paragraph, "which loop they are on" is wrong.  It should be "which time through the loop."

In the shaded boxes, is there a reason you changed the word "variable" to "counter"?  The whole point here is that we're using the variable in the FOR block as the introduction to variables in general, not all of which are counters.  I'm guessing you thought "counter" would be less intimidating, but they have to learn "variable" eventually and we don't want them to learn it in the context of global ones.

I like the animation of dragging the variable into the SAY block!

**Comment by xtitter** [comment]
The term variable could be introduced here, or when we introduce inputs to custom blocks, or in topic 3 when they are treated more fully (with "script local" and "set").  I guess I though the last was best, because 'set' gave them the real sense of variable.  

I could see doing it with FOR though, since it is actually varying here.  The 'custom block w/ inputs' is the worst choice, since the value is static inside the block (for all they know at this point).

If 'counter' isn't a good term, then I could do 'variable' here, and introduce the idea that it is a 'box that holds a (maybe changing) value'. Hm, but that doesn't distinguish it from (x pointer) does it. I guess I still like doing it in topic 3.

**Comment by brianharvey** [comment]
> because 'set' gave them the real sense of variable.

NOOOOOOOOOOOOOO!!!!!!!!

SET gives them the real sense of how to write bad programs.  Let's take advantage of the fact that in high school algebra they learned to think of a variable as "a constant whose value we don't know yet" to encourage good (i.e., functional) programming.

This was the entire purpose of introducing FOR so early!  It was so that they would learn what a variable is before they're tempted actually to vary one.  And, of course, because its scope is automatically and naturally limited.

X POSITION is not a /box/ at all.  You call it, and it looks at the sprite to see where it is right now.  It's kind of too bad that you can set a watcher for it.  But that's a much more complicated semantic argument you can have with yourself on the weekends; the /important/ point is that this orange oval thing is called a variable.

**Comment by xtitter** [comment]
eh, fine.
