### ISSUE TITLE
Make "Solutions" Page

### ISSUE THREAD

**Issue by peterasujan** [cs10/bjc-r#233]
Now that we're generating more solutions files, there should be a course- or topic-like page that links to all of them.

**Comment by cycomachead** [comment]
We also need a solutions directory. (in the repo, unless there is one already.)

I'm not sure a full solutions page was desired at one one, according to something @xtitter Said once.. However, I agree we should have them organized somewhere.

I would also like to have conditional loading of solutions. Essentially, the idea is this:
Each course has a date associated with each lab, ideally the date the lab is assigned. After DATE + N days, the link to the solutions is shown in some appropriate place. The goal here is to give students solutions, but to try to ensure they complete the lab first. Essentially, I just want to protect people from crazy temptation not from completely searching for solutions.

**Comment by peterasujan** [comment]
Currently we've been dropping them in prog/something. We can make a directory under prog, methinks.
I do see where you're coming from. I like the date idea, and it'd be pretty doable in straight js.

**Comment by cycomachead** [comment]
Yep, it would be. I should standardize this is... There's code in
weekly.html under the sp14 site that does it for the CS10 calendar already.

I also like the idea of one directory for solutions, because it's very easy
to chmod 600 the whole directory if you need to hide solutions.

We also need to decide whether solutions are per-lab or per-page 'problem'
(which makes more sense given our structure) but could be more work.
Along those lines we should try to standardize some format of comments and
explanations in solutions, but this isn't a huge deal.

## 

Michael Ball
http://www.michaelballphoto.com
Photos & iPhone Apps

**Comment by peterasujan** [comment]
Good point.

Currently we've been just doing one per lab. I'll definitely make sure that they're well commented before publishing.

**Comment by cycomachead** [comment]
@xtitter CS10 students definitely want solutions. 

Aside from getting organized, we should definitely find a way to track them and possibly present them to students. I'd like to be able to just set a list of dates and auto-release solutions, instead of remembering, but that still might be problematic for HS.

**Comment by peterasujan** [comment]
We were discussing this a bit during lab dev yesterday. Possibly we could release them through bCourses/edX so they're not completely accessible to the world. It's also common for classes to post their solutions in a physical location where students have to actual go there to see them. It might be a bit weird to print out Snap! code, but it could work okay, I think.

**Comment by cycomachead** [comment]
Gonna close this because what we really need is a good way for teachers to get solutions. bCourses will work well for CS10. :+1:
