### ISSUE TITLE
Intro / Getting Started Guide for Working on Labs?

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#29]
Is there any documentation for how to write a lab, or resources for getting started with code and building the lab site? 

Most of it looks pretty straight-forward, but it would be great to have some docs to help getting started, hopefully covering things like style and conventions. This could really help as we get others involved in working on updating labs.

**Comment by xtitter** [comment]
All documentation is going into the beautyjoy/bjc-teacher-resoucers repository, which is hosted at http://bjc.berkeley.edu/teacher-resources/  (at the github.io one, except that is annoying because it the github server doesn't list directory contents)

Right now there is _very_ little there; just a quick job to get something up.  The one how-to page is really focused on navigating github -- how to fork, make pull requests, etc.  

Arg, I'll try to get something up in http://bjc.berkeley.edu/teacher-resources/authoring/authoring.html soon
