### ISSUE TITLE
moving LLAB out to its own repo

### ISSUE THREAD

**Issue by xtitter** [cs10/bjc-r#332]
So, don't make any more changes in /admin in this repo... or, if you have to, make sure you either get or will eventually get the functionality over to the corresponding parts of the llab repo.

There will be changes to make here when we are ready to merge llab back in:
- [x] get rid of /admin, and make a submodule from the llab repo
- [x] fix content: reference the new loader file name/location
- [ ] did we fix the repo-root issue in llab?  If so, fix every absolute link to do the right thing

more...

@gissues:{"order":87.5,"status":"inprogress"}

**Comment by cycomachead** [comment]
We haven't fixed the absolute links, and I don't know if there's a good way to...

We could mitigate the problem by always pointing to topic.html which loads the right page, and individual content pages are merely included via XHRs but it could then be slightly trickier to link to individual pages/

**Comment by xtitter** [comment]
Well, I'm doing a lot of stuff in llab -- making a 'config.js' that should have most of the install details.  Maybe this will fix things.  

With all the "bjc-r" in the content files themselves, though, there isn't much to be done when you what to install it on a different server configuration (ala cs10).  I guess you could convince me to to relative links everywhere.

**Comment by cycomachead** [comment]
Relative links everywhere make the severing problem somewhat easy, but they can also make a build process tricker too. It's a toss up, but I generally prefer relative links. 

Well, I was still working on the bootstrap pull request. I've been refactoring a lot of bjc-course so it can hopefully be more generic. 

One location to edit will still help, but if we're ever expecting files to be in some location like `/bjc-r` we will always run into the issue of needing to find and replace... At least to my understanding. 

Also, how will the config.js work? Because we can't so it in the repo if there's supposed to be a single repo. (I guess it could be a small step to just keep it on the server, and gitignore the file...)

**Comment by xtitter** [comment]
I don't understand all of this.  

Did I get all your refactorings in course.js when I 'moved' it into the llab repo?  

Will the stuff I put in to the llab repo in config.js fix the CS10 issues?  Or course, I haven't particularly tested different server configurations, but my limited tests worked.  Check it out.

**Comment by cycomachead** [comment]
I'll take a look tonight, but I don't think you did, because #270 hasn't been merged. It's OK though. I'm probably going to work off that branch for a bit longer while you're still working on the separation, then manually diff things and merge myself.

I also just had a super interesting meeting about web performance so I've got some thoughts on things we can do to optimize page loads.

**Comment by cycomachead** [comment]
1 and 2 are done. The whole server root url thing is still to be figured out. I don't like that there's 2 places needed for a config and that they both reside in the llab repo which in theory makes dealing with branching and multiple sites tricky.

I think we can probably figure something out with URL parsing and it should work fine. :)
