### ISSUE TITLE
Why did forward/back go away from the bottom of the page?

### ISSUE THREAD

**Issue by xtitter** [cs10/bjc-r#363]
That was _really_ useful I thought

**Comment by cycomachead** [comment]
Awww. Recent merge??? It is really helpful! :D look at the issues which just got (auto, I might add!) posted.

**Comment by cycomachead** [comment]
Edit, wait, never mind. Yeah, it's gone. I can fix it this weekend... But I thought it was mainly because we have a sticky nav. But the mouse movement is awkward. So I will work on styling it back in. 
(The code is fairly generic :D)

@xtitter Do you have a preference to both buttons on the right, or one on the left and the other on the right?

**Comment by cycomachead** [comment]
I'll fix this with llab integration so we won't duplicate too much work. And I've styled them a little more nicely. :)

**Comment by cycomachead** [comment]
Closing this because it _will_ be fixed soon!
