### ISSUE TITLE
How do I run my own server for testing?

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#47]
Currently, I've only been pushing to GH to test my changes. Can I setup a server locally?

**Comment by xtitter** [comment]
For sure -- its like running any server locally, which will be different for Macs versus windows versus ...  I have apache on a windows machine, cloned my git repo into a 'bjc-r' directory, and then have an Alias directive in the http.conf.  Or, you could clone right into 'doc-root/bjc-r'.

I think it has to be served via "localhost/bjc-r/" though, because all the curriculum and topics are written in that way.  It would be nice if we make it so that the repo could be place anywhere within a domain.

**Comment by cycomachead** [comment]
I wasn't able to get my httpd.conf file modified correctly, but I can mess around with OS X implementation of Safari to get the labs to build when served at localhost/bjc-r/

I'll probably add something to the readme soon.
