### ISSUE TITLE
Remove add Height and Width Properties from images?

### ISSUE THREAD

**Issue by cycomachead** [cs10/bjc-r#52]
Is there any reason to have hard coded properties in /every/ /single/ tag for images? There are way too many places right now that have Snap! Images which are squished in some dimension because their properties are different from BYOB.

If no one has any objections, I think it would be good to run the following regex over the /bjc-r folder for _.html files
    (width|height|vspace|hspace)="\d_"\s+

On my system it finds 2,268 matches all of which are contained in `<img />` so it would seem relatively safe to proceed. I'm going to test with a test branch shortly...

**Comment by sean-morris** [comment]
The reason for keeping height and width attributes on img tags is to
increase rendering speed. If the height and width attributes are the exact
height and width of the image being rendered the speed of page load is
enhanced. I wouldn't get rid of them. My guess is that moodle was handling
this well.

If you do not include height and width the page is essentially laid out
twice by the browser. The first is before reading the CSS file in which the
img tags are placeholders but the wrong size and then again after the CSS
is read and the correct height and width are applied.

Hope that helps.

**Comment by cycomachead** [comment]
Thanks! I didn't realize browsers treated them that way. Now I must update my own site... :P

I'll take a look and see if I can easily script a fix for all the width and height issues.

**Comment by xtitter** [comment]
Well, I've been removing them whenever I replace an image, rather than fixing them for the new image. The existing height and width stuff was put in by Moodle -- and Sean nicely explains why, which I didn't know.  But, I'd rather waste the client computers time than mine when I manually update images! 

 I guess Brian didn't remove the heigh/width (and border, etc) attributes when he updated the image srcs.   We do need to fix each of those, and it is hard to know which ones Brian fixed and which ones he didn't. (Although, that could be done in an automated way, based on create date in the /img folder).

I'm ok with blowing them all away, thinking that it is better to have no squashed images than speeding up browser load times.

**Comment by cycomachead** [comment]
Alright.

My other thought was a python script which would read the image file, and
do string string replacement on the source.

## 

Michael Ball
http://www.michaelballphoto.com
Photos & iPhone Apps!

**Comment by cycomachead** [comment]
Fixed with #70
