### ISSUE TITLE
Algorithms Lab - Testing time

### ISSUE THREAD

**Issue by jcmack** [cs10/bjc-r#75]
For the find the number in unsorted list block, repeat 20 takes a really long time to execute. Can we change this or warn the students in the lab text it'll take a long time? Several students were concerned their code was broken when it wasn't.

**Comment by peterasujan** [comment]
Agreed. Perhaps we could recommend they try their block separately, then add it to the larger script.

**Comment by aaaschmitt** [comment]
I am changing the number of repeats to 10 and I have also changed some of the comments to make it clearer that the script is only testing the block that they write.  I have also dropped physical inputs into the unsorted finder block so that students can manually test before running the testing script (this was already done for the binary search block...) -> comments also encourage students to manually test first.

I am keeping the old framework file for reference but the page will now link to the new file: algorithms-framework-new.

**Comment by cycomachead** [comment]
> I am changing the number of repeats to 10 and I have also changed some of the comments to make it clearer that the script is only testing the block that they write. I have also dropped physical inputs into the unsorted finder block so that students can manually test before running the testing script (this was already done for the binary search block...) -> comments also encourage students to manually test first.

I don't know if the comments are still there, but we should have a note that 10 is too few iterations on newer computers. This is especially true for the memorized version, otherwise it won't seem faster than binary search.

**Comment by aaaschmitt** [comment]
The comment noting that the initial settings may need to be changed to see a noticeable difference in time is still there.  20 takes too long. very few students end up running the testing script.  

They should be testing on their own initially anyways --> binary search might actually be a good place to talk about edge cases which is another open issue
