### ISSUE TITLE
Teacher Guide login

### ISSUE THREAD

**Issue by CFKaligula** [cs10/bjc-r#864]
I'm part of the team that translates the BJC material to Dutch: [our work is found here](www.bjoc.nl). 

As you can see, we translated an older version of the material. We would also like to translate the teacher's guide. I found the compatible teacher guide [here](https://bjc.edc.org/March2019/bjc-r/course/bjc4nyc_teacher.html), but for most of the web pages it seems I need to log in. Could you give any help with either login credentials or some other way, so I could view this material?

Not sure if this is the right way to contact you about this, if it is not, I would also gladly  discuss this via some other way.

**Comment by cycomachead** [comment]
Hi there!

For the password protected pages: There's not too much there, mostly links to our solutions. We'd be happy to share the password. Please fill out the form at https://teachers.bjc.berkeley.edu -- anyone on your team is welcome to fill it out. We will then send you an email with the password and instructions for accessing the solutions.

Otherwise, please feel free to reach out to contact@bjc.berkeley.edu with any questions. That goes to the whole team, so you'll often get a response faster than just me.

**Comment by CFKaligula** [comment]
Thank you!
